# Generated by Django 5.2.3 on 2025-10-21 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('profissional', 'Profissional')], max_length=15)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.CharField(blank=True, max_length=255, null=True)),
                ('visivel', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_atuacao', models.CharField(blank=True, max_length=100, null=True)),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('nota_media', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('bio', models.TextField(blank=True, null=True)),
                ('imagem_portfolio', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.perfil')),
            ],
        ),
    ]
