# Generated by Django 5.2.3 on 2025-11-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField(db_column='data')),
                ('horario', models.TimeField()),
                ('status', models.CharField(default='Agendado', max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'agendamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('imagem', models.CharField(blank=True, max_length=255, null=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ferramenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('profissional', 'Profissional'), ('cliente', 'Cliente')], max_length=12)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.CharField(blank=True, max_length=255, null=True)),
                ('visivel', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_atuacao', models.CharField(blank=True, max_length=100, null=True)),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('nota_media', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('bio', models.TextField(blank=True, null=True)),
                ('imagem_portfolio', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'profissional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('foto', models.CharField(blank=True, db_column='imagem', max_length=255, null=True)),
                ('aprovado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'servico',
                'managed': False,
            },
        ),
    ]
